###########################################################
### Configuration for Patent-Job Relationship Website
### Adapted from Beautiful Jekyll configuration template
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: Patent-Job Relationship Analysis

# Your name to show in the footer
author: Joanne Atallah

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Home: "/"
  Graphs: "/graphs"
  Tables: "/tables"
  Resources:
    - Learn Markdown: "https://www.markdowntutorial.com/"
    - Beautiful Jekyll: "https://beautifuljekyll.com"

################
# --- Logo --- #
################

# Remove avatar to simplify the design for this academic project
# avatar: "/assets/img/avatar-icon.png"
# round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

# Relevant links for the project
social-network-links:
  email: "joanne.atallah@example.com"
  github: "your-github-username"
  linkedin: "your-linkedin-username"

###########################
# --- General options --- #
###########################

# Enable search functionality
post_search: true

# Add the website title to every page
title-on-all-pages: true

# Display tags below each blog post preview
feed_show_tags: true

######################################
# --- Colours / background image --- #
######################################

# Customize colours for a clean and professional look
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#007BFF"
hover-col: "#0056b3"
navbar-col: "#f8f9fa"
navbar-text-col: "#000000"
footer-col: "#f8f9fa"
footer-text-col: "#6c757d"
footer-link-col: "#007BFF"
footer-hover-col: "#0056b3"

# Optionally add a background image to the page
# page-img: "/assets/img/bgimage.png"

#################################
# --- Web Analytics Section --- #
#################################

# Add your Google Analytics ID to track traffic (optional)
# gtag: "G-XXXXXXXXXX"

################
# --- Misc --- #
################

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Exclude unnecessary files from the production site
exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/

# Jekyll plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

###########################################################
# --- Custom Sections for Patent-Job Analysis Project --- #
###########################################################

# Define additional configurations or meta tags as required
custom_sections:
  graphs-section:
    title: "Graphs"
    description: "Explore our visual analysis of the relationship between patents and job openings."
  tables-section:
    title: "Statistical Tables"
    description: "Dive into detailed tables showcasing key data from our analysis."

